#!/usr/bin/env node
/**
 * Herald Init - Create .env template for Herald MCP configuration
 * 
 * CEDA-54: Seamless onboarding with sensible defaults
 * 
 * Usage:
 *   npx herald init
 *   yarn herald:init
 */

import * as fs from 'fs';
import * as path from 'path';

const ENV_TEMPLATE = `# Herald MCP Configuration
# Generated by: npx herald init
# Documentation: https://getceda.com/docs/herald

# CEDA Server URL (default: https://getceda.com)
CEDA_URL=https://getceda.com

# Your company identifier (required for multi-tenant pattern isolation)
# Example: HERALD_COMPANY=acme-corp
HERALD_COMPANY=

# Your project identifier (optional, for project-scoped patterns)
# Example: HERALD_PROJECT=safety-app
HERALD_PROJECT=

# Session ID prefix (optional, auto-generated if not set)
# HERALD_SESSION_ID=

# User identifier (optional, set per-request or here for default)
# HERALD_USER=
`;

function main(): void {
  const targetPath = path.join(process.cwd(), '.env');
  const templatePath = path.join(process.cwd(), '.env.herald.template');
  
  console.log('Herald Init - Setting up Herald MCP configuration\n');
  
  // Check if .env already exists
  if (fs.existsSync(targetPath)) {
    console.log('Found existing .env file.');
    console.log(`Writing template to ${templatePath} instead.\n`);
    
    fs.writeFileSync(templatePath, ENV_TEMPLATE);
    console.log(`Created: ${templatePath}`);
    console.log('\nTo use Herald defaults, merge the template into your .env file.');
  } else {
    fs.writeFileSync(targetPath, ENV_TEMPLATE);
    console.log(`Created: ${targetPath}\n`);
  }
  
  console.log('\nNext steps:');
  console.log('  1. Edit .env and set HERALD_COMPANY to your company identifier');
  console.log('  2. Optionally set HERALD_PROJECT for project-scoped patterns');
  console.log('  3. Run Herald: npx herald');
  console.log('\nHerald works out of the box with https://getceda.com (zero-config).');
  console.log('For local development, set CEDA_URL=http://localhost:3030');
}

main();
